FROM registry.access.redhat.com/ubi9/go-toolset:1.20 AS builder

USER 1000

COPY . .

RUN chgrp -R root ./src && chmod g+rwX ./src
RUN go mod tidy && go build -o client client.go

FROM registry.access.redhat.com/ubi9/micro:9.3

USER 1000

WORKDIR /app
COPY --from=builder /opt/app-root/src/client /app/client

ENTRYPOINT ["/app/client"]