FROM registry.access.redhat.com/ubi9/go-toolset:1.20 AS builder

USER 10001

COPY . /opt/app-root/src

WORKDIR /opt/app-root/src
RUN go mod tidy && go build -o client

FROM registry.access.redhat.com/ubi9/micro:9.3

USER 10001

WORKDIR /app
COPY --from=builder /opt/app-root/src/client /app/client

ENTRYPOINT ["/app/client"]